import type { CommercialTerritoryId } from "./territories";

export type CommercialProfileId =
  | "hm_highmil_lubricants"
  | "primasa_printing"
  | "coformex_printing"
  | "uniforce_security_risk"
  | "grupo_constructor_nag_construction";

export interface CommercialProfile {
  id: CommercialProfileId;
  companyName: string;
  displayName: string;
  businessLines: string[];
  territories: CommercialTerritoryId[];
  primaryKeywords: string[];
  secondaryKeywords: string[];
  negativeKeywords: string[];
  strongContextKeywords: string[];
  weakContextKeywords: string[];
  preferredBuyerTypes: string[];
  sourcePriority: string[];
  minScore: number;
  alertEnabled: boolean;
}

export const STRONG_COMMERCIAL_CONTEXT_KEYWORDS = [
  "licitacion",
  "licitación",
  "contratacion",
  "contratación",
  "adquisicion",
  "adquisición",
  "suministro",
  "servicio",
  "convocatoria",
  "invitacion",
  "invitación",
  "adjudicacion",
  "adjudicación",
  "arrendamiento",
  "mantenimiento",
  "obra",
  "remodelacion",
  "remodelación",
  "rehabilitacion",
  "rehabilitación",
  "compra",
  "proveedor",
  "cotizacion",
  "cotización",
  "procedimiento",
  "fallo",
  "junta de aclaraciones",
  "bases",
  "anexo tecnico",
  "anexo técnico",
];

const TARGET_TERRITORIES: CommercialTerritoryId[] = [
  "morelos",
  "jalisco_guadalajara",
  "cdmx",
  "edomex",
];

const PRINTING_PRIMARY_KEYWORDS = [
  "impreso",
  "impresos",
  "impresion",
  "impresión",
  "impresiones",
  "material impreso",
  "formatos impresos",
  "papeleria impresa",
  "papelería impresa",
  "folletos",
  "tripticos",
  "trípticos",
  "dipticos",
  "dípticos",
  "carteles",
  "lonas",
  "viniles",
  "etiquetas",
  "credenciales",
  "gafetes",
  "impresion digital",
  "impresión digital",
  "impresion offset",
  "impresión offset",
  "servicios de impresion",
  "servicios de impresión",
];

const PRINTING_SECONDARY_KEYWORDS = [
  "material de difusion",
  "material de difusión",
  "material grafico",
  "material gráfico",
  "papeleria institucional",
  "papelería institucional",
  "formas valoradas",
  "boletos",
  "recibos",
  "talonarios",
  "libros",
  "revistas",
  "cuadernillos",
  "manuales",
  "constancias",
  "diplomas",
  "hojas membretadas",
  "sobres",
  "flyers",
  "banners",
];

const PRINTING_NEGATIVE_KEYWORDS = [
  "impresion diagnostica",
  "impresión diagnóstica",
  "impresion medica",
  "impresión médica",
  "imagenologia",
  "imagenología",
  "tomografia",
  "tomografía",
  "rayos x",
  "impresion 3d medica",
  "impresión 3d médica",
  "impresora",
  "toner solamente",
  "tóner solamente",
  "cartucho solamente",
];

export const COMMERCIAL_PROFILES: CommercialProfile[] = [
  {
    id: "hm_highmil_lubricants",
    companyName: "HM HIGHMIL",
    displayName: "HM HIGHMIL - Lubricantes y anticongelantes",
    businessLines: ["Aceites", "Aditivos", "Grasas", "Anticongelantes"],
    territories: TARGET_TERRITORIES,
    primaryKeywords: [
      "aceite",
      "aceites",
      "lubricante",
      "lubricantes",
      "aceite lubricante",
      "aceite automotriz",
      "aceite para motor",
      "aceite hidraulico",
      "aceite hidráulico",
      "aceite industrial",
      "grasa",
      "grasas",
      "grasa lubricante",
      "aditivo",
      "aditivos",
      "anticongelante",
      "anticongelantes",
      "refrigerante automotriz",
      "liquido refrigerante",
      "líquido refrigerante",
    ],
    secondaryKeywords: [
      "mantenimiento vehicular",
      "parque vehicular",
      "vehiculos oficiales",
      "vehículos oficiales",
      "flotilla vehicular",
      "maquinaria",
      "equipo pesado",
      "talleres",
      "refacciones",
      "refacciones y lubricantes",
      "insumos automotrices",
      "servicio automotriz",
      "mantenimiento de unidades",
    ],
    negativeKeywords: [
      "aceite comestible",
      "aceite vegetal",
      "aceite de cocina",
      "grasa alimenticia",
      "aceites vegetales",
      "alimentos",
      "cocina",
      "comedor",
      "despensa",
    ],
    strongContextKeywords: STRONG_COMMERCIAL_CONTEXT_KEYWORDS,
    weakContextKeywords: ["vehicular", "automotriz", "flotilla", "maquinaria"],
    preferredBuyerTypes: ["gobierno", "municipio", "ayuntamiento", "organismo publico", "universidad publica"],
    sourcePriority: ["comprasmx", "dof", "datos.gob.mx", "official_website"],
    minScore: 60,
    alertEnabled: true,
  },
  {
    id: "primasa_printing",
    companyName: "PRIMASA",
    displayName: "PRIMASA - Impresos y material grafico",
    businessLines: ["Impresos", "Material grafico"],
    territories: TARGET_TERRITORIES,
    primaryKeywords: PRINTING_PRIMARY_KEYWORDS,
    secondaryKeywords: PRINTING_SECONDARY_KEYWORDS,
    negativeKeywords: PRINTING_NEGATIVE_KEYWORDS,
    strongContextKeywords: STRONG_COMMERCIAL_CONTEXT_KEYWORDS,
    weakContextKeywords: ["campaña institucional", "difusion", "difusión", "papeleria", "papelería"],
    preferredBuyerTypes: ["gobierno", "municipio", "ayuntamiento", "instituto", "universidad publica"],
    sourcePriority: ["comprasmx", "dof", "datos.gob.mx", "official_website"],
    minScore: 60,
    alertEnabled: true,
  },
  {
    id: "coformex_printing",
    companyName: "COFORMEX",
    displayName: "COFORMEX - Impresos y material grafico",
    businessLines: ["Impresos", "Material grafico"],
    territories: TARGET_TERRITORIES,
    primaryKeywords: PRINTING_PRIMARY_KEYWORDS,
    secondaryKeywords: PRINTING_SECONDARY_KEYWORDS,
    negativeKeywords: PRINTING_NEGATIVE_KEYWORDS,
    strongContextKeywords: STRONG_COMMERCIAL_CONTEXT_KEYWORDS,
    weakContextKeywords: ["campaña institucional", "difusion", "difusión", "papeleria", "papelería"],
    preferredBuyerTypes: ["gobierno", "municipio", "ayuntamiento", "instituto", "universidad publica"],
    sourcePriority: ["comprasmx", "dof", "datos.gob.mx", "official_website"],
    minScore: 60,
    alertEnabled: true,
  },
  {
    id: "uniforce_security_risk",
    companyName: "UNIFORCE",
    displayName: "UNIFORCE - Seguridad, confianza y evaluaciones",
    businessLines: [
      "Diagnostico personal de riesgo",
      "Control de confianza",
      "Evaluacion psicometrica",
      "Seguridad intramuros",
      "Guardias de seguridad",
    ],
    territories: TARGET_TERRITORIES,
    primaryKeywords: [
      "seguridad privada",
      "guardia de seguridad",
      "guardias de seguridad",
      "guardia armado",
      "guardias armados",
      "guardia desarmado",
      "guardias desarmados",
      "seguridad intramuros",
      "vigilancia",
      "servicio de vigilancia",
      "control de confianza",
      "evaluacion psicometrica",
      "evaluación psicométrica",
      "evaluaciones psicometricas",
      "evaluaciones psicométricas",
      "evaluacion socioeconomica",
      "evaluación socioeconómica",
      "estudio socioeconomico",
      "estudio socioeconómico",
      "analisis de riesgo",
      "análisis de riesgo",
      "diagnostico de riesgo",
      "diagnóstico de riesgo",
      "validacion de documentos",
      "validación de documentos",
      "verificacion documental",
      "verificación documental",
      "evaluacion de solvencia",
      "evaluación de solvencia",
      "estudio de solvencia",
      "evaluacion de autotransporte",
      "evaluación de autotransporte",
      "seguridad patrimonial",
    ],
    secondaryKeywords: [
      "acceso controlado",
      "caseta de vigilancia",
      "proteccion de instalaciones",
      "protección de instalaciones",
      "rondines",
      "monitoreo de seguridad",
      "seguridad institucional",
      "personal de seguridad",
      "revision documental",
      "revisión documental",
      "antecedentes laborales",
      "investigacion socioeconomica",
      "investigación socioeconómica",
      "evaluacion de personal",
      "evaluación de personal",
      "filtros de confianza",
      "perfilamiento de riesgo",
    ],
    negativeKeywords: [
      "seguridad informatica",
      "seguridad informática",
      "ciberseguridad",
      "firewall",
      "antivirus",
      "licencias de seguridad",
      "camaras solamente",
      "cámaras solamente",
      "videovigilancia solamente",
      "software de seguridad",
      "seguridad de la informacion",
      "seguridad de la información",
      "proteccion de datos",
      "protección de datos",
      "seguridad alimentaria",
    ],
    strongContextKeywords: STRONG_COMMERCIAL_CONTEXT_KEYWORDS,
    weakContextKeywords: ["seguridad", "riesgo", "personal", "instalaciones"],
    preferredBuyerTypes: ["gobierno", "municipio", "ayuntamiento", "organismo publico", "hospital publico"],
    sourcePriority: ["comprasmx", "dof", "datos.gob.mx", "official_website"],
    minScore: 60,
    alertEnabled: true,
  },
  {
    id: "grupo_constructor_nag_construction",
    companyName: "GRUPO CONSTRUCTOR NAG, S.A. de C.V.",
    displayName: "GRUPO CONSTRUCTOR NAG - Construccion, remodelacion y mantenimiento",
    businessLines: ["Construccion", "Remodelacion", "Mantenimiento"],
    territories: TARGET_TERRITORIES,
    primaryKeywords: [
      "construccion",
      "construcción",
      "obra civil",
      "remodelacion",
      "remodelación",
      "mantenimiento",
      "mantenimiento preventivo",
      "mantenimiento correctivo",
      "rehabilitacion",
      "rehabilitación",
      "conservacion",
      "conservación",
      "reparacion",
      "reparación",
      "adecuacion",
      "adecuación",
      "ampliacion",
      "ampliación",
      "instalaciones",
      "infraestructura",
      "albañileria",
      "albañilería",
      "pintura",
      "impermeabilizacion",
      "impermeabilización",
      "herreria",
      "herrería",
      "plomeria",
      "plomería",
      "electricidad",
      "acabados",
      "mantenimiento de inmuebles",
      "mantenimiento de edificios",
      "mantenimiento de oficinas",
    ],
    secondaryKeywords: [
      "obra publica",
      "obra pública",
      "conservacion de inmuebles",
      "conservación de inmuebles",
      "rehabilitacion de espacios",
      "rehabilitación de espacios",
      "reparacion de instalaciones",
      "reparación de instalaciones",
      "mantenimiento general",
      "trabajos de construccion",
      "trabajos de construcción",
      "servicios de mantenimiento",
      "adecuacion de espacios",
      "adecuación de espacios",
      "rehabilitacion de oficinas",
      "rehabilitación de oficinas",
      "mantenimiento a instalaciones",
      "mantenimiento de escuelas",
      "mantenimiento de hospitales",
      "mantenimiento de edificios publicos",
      "mantenimiento de edificios públicos",
    ],
    negativeKeywords: [
      "mantenimiento de software",
      "licencias de software",
      "soporte tecnico",
      "soporte técnico",
      "mantenimiento informatico",
      "mantenimiento informático",
      "mantenimiento de servidores",
      "mantenimiento de sistemas",
      "mantenimiento de computadoras",
      "mantenimiento de equipos de computo",
      "mantenimiento de equipos de cómputo",
      "mantenimiento de impresoras",
      "computadoras e impresoras",
      "computadoras",
      "impresoras",
      "mantenimiento vehicular",
      "parque vehicular",
      "flotilla vehicular",
      "vehiculos oficiales",
      "vehículos oficiales",
      "unidades vehiculares",
      "mantenimiento automotriz",
      "servicio automotriz",
      "taller mecanico",
      "taller mecánico",
      "talleres mecanicos",
      "talleres mecánicos",
      "refacciones vehiculares",
      "mantenimiento de vehiculos",
      "mantenimiento de vehículos",
      "mantenimiento a vehiculos",
      "mantenimiento a vehículos",
      "mantenimiento de unidades",
      "mantenimiento a unidades",
    ],
    strongContextKeywords: STRONG_COMMERCIAL_CONTEXT_KEYWORDS,
    weakContextKeywords: ["inmuebles", "edificios", "oficinas", "espacios", "instalaciones"],
    preferredBuyerTypes: ["gobierno", "municipio", "ayuntamiento", "escuela", "hospital publico"],
    sourcePriority: ["comprasmx", "dof", "datos.gob.mx", "official_website"],
    minScore: 60,
    alertEnabled: true,
  },
];

export function getCommercialProfile(id: CommercialProfileId): CommercialProfile {
  const profile = COMMERCIAL_PROFILES.find((item) => item.id === id);
  if (!profile) throw new Error(`Commercial profile not found: ${id}`);
  return profile;
}
