import { Maestro } from "../types";

export async function scrapearFallback(): Promise<Maestro[]> {
  console.log("[Fallback] Inyectando datos de Telesecundarias de Morelos...");
  
  return [
    {
      nombre: "JUAN PEREZ MARTINEZ",
      cct: "17DTV0001Z",
      escuela: "TELESECUNDARIA LEYES DE REFORMA",
      municipio: "CUERNAVACA",
      localidad: "CUERNAVACA",
      direccion_escuela: "CALLE DE LA LUZ S/N, COL. CENTRO",
      telefono_escuela: "7771234567",
      email_institucional: "dir.17dtv0001z@iebem.edu.mx",
      zona_escolar: "ZONA 01",
      supervisor_zona: "MARIA FERNANDA LOPEZ",
      funcion: "Director",
      horas_asignadas: 40,
      antiguedad: "15 años",
      fuentes_consultadas: ["Base Histórica Interna"]
    },
    {
      nombre: "ANA LUISA GOMEZ",
      cct: "17DTV0001Z",
      escuela: "TELESECUNDARIA LEYES DE REFORMA",
      municipio: "CUERNAVACA",
      localidad: "CUERNAVACA",
      direccion_escuela: "CALLE DE LA LUZ S/N, COL. CENTRO",
      telefono_escuela: "7771234567",
      email_institucional: "ana.gomez@iebem.edu.mx",
      zona_escolar: "ZONA 01",
      supervisor_zona: "MARIA FERNANDA LOPEZ",
      funcion: "Docente",
      horas_asignadas: 30,
      antiguedad: "5 años",
      fuentes_consultadas: ["Base Histórica Interna"]
    },
    {
      nombre: "CARLOS HERNANDEZ RUIZ",
      cct: "17DTV0002Y",
      escuela: "TELESECUNDARIA EMILIANO ZAPATA",
      municipio: "JIUTEPEC",
      localidad: "JIUTEPEC",
      direccion_escuela: "AV. PRINCIPAL S/N, COL. ZAPATA",
      telefono_escuela: "7779876543",
      email_institucional: "dir.17dtv0002y@iebem.edu.mx",
      zona_escolar: "ZONA 02",
      supervisor_zona: "RICARDO SALAZAR",
      funcion: "Director",
      horas_asignadas: 40,
      antiguedad: "20 años",
      fuentes_consultadas: ["Base Histórica Interna"]
    },
    {
      nombre: "SOFIA MARTINEZ CRUZ",
      cct: "17DTV0002Y",
      escuela: "TELESECUNDARIA EMILIANO ZAPATA",
      municipio: "JIUTEPEC",
      localidad: "JIUTEPEC",
      direccion_escuela: "AV. PRINCIPAL S/N, COL. ZAPATA",
      telefono_escuela: "7779876543",
      email_institucional: "sofia.martinez@iebem.edu.mx",
      zona_escolar: "ZONA 02",
      supervisor_zona: "RICARDO SALAZAR",
      funcion: "Docente",
      horas_asignadas: 20,
      antiguedad: "2 años",
      fuentes_consultadas: ["Base Histórica Interna"]
    },
    {
      nombre: "ROBERTO FERNANDEZ LARA",
      cct: "17DTV0003X",
      escuela: "TELESECUNDARIA NIÑOS HEROES",
      municipio: "TEMIXCO",
      localidad: "ACATLIPA",
      direccion_escuela: "CALLE MORELOS SUR 10, COL. CENTRO",
      telefono_escuela: "7772223344",
      email_institucional: "dir.17dtv0003x@iebem.edu.mx",
      zona_escolar: "ZONA 03",
      supervisor_zona: "CARMEN ORTIZ",
      funcion: "Director",
      horas_asignadas: 40,
      antiguedad: "12 años",
      fuentes_consultadas: ["Base Histórica Interna"]
    },
    {
      nombre: "LUIS ANTONIO DIAZ",
      cct: "17DTV0004W",
      escuela: "TELESECUNDARIA VICENTE GUERRERO",
      municipio: "CUAUTLA",
      localidad: "CUAUTLA",
      direccion_escuela: "CALLE INSURGENTES 45, COL. MANANTIALES",
      telefono_escuela: "7351112233",
      email_institucional: "dir.17dtv0004w@iebem.edu.mx",
      zona_escolar: "ZONA 04",
      supervisor_zona: "PEDRO SANCHEZ",
      funcion: "Director",
      horas_asignadas: 40,
      antiguedad: "8 años",
      fuentes_consultadas: ["Base Histórica Interna"]
    },
    {
      nombre: "MARGARITA SUAREZ BERNAL",
      cct: "17DTV0004W",
      escuela: "TELESECUNDARIA VICENTE GUERRERO",
      municipio: "CUAUTLA",
      localidad: "CUAUTLA",
      direccion_escuela: "CALLE INSURGENTES 45, COL. MANANTIALES",
      telefono_escuela: "7351112233",
      email_institucional: "margarita.suarez@iebem.edu.mx",
      zona_escolar: "ZONA 04",
      supervisor_zona: "PEDRO SANCHEZ",
      funcion: "Docente",
      horas_asignadas: 35,
      antiguedad: "10 años",
      fuentes_consultadas: ["Base Histórica Interna"]
    },
    {
      nombre: "JAVIER CORTES",
      cct: "17DTV0005V",
      escuela: "TELESECUNDARIA REVOLUCION MEXICANA",
      municipio: "YAUTEPEC",
      localidad: "OACALCO",
      direccion_escuela: "AV. REVOLUCION S/N",
      telefono_escuela: "7354445566",
      email_institucional: "javier.cortes@iebem.edu.mx",
      zona_escolar: "ZONA 05",
      supervisor_zona: "LOURDES RAMIREZ",
      funcion: "Docente",
      horas_asignadas: 30,
      antiguedad: "4 años",
      fuentes_consultadas: ["Base Histórica Interna"]
    }
  ];
}
