/**
 * RADAR: capufe_mantenimiento_equipos
 * OBJETIVO PRINCIPAL: Detectar la licitación de mantenimiento preventivo y correctivo
 * a equipos de control de tránsito de peaje y telepeaje en plazas de cobro de la
 * red FONADIN y tramo México-Puebla, emitida por CAPUFE.
 */
import type { RadarConfig } from "../types/procurement";

export const capufeMantenimientoEquiposRadar: RadarConfig = {
  key: "capufe_mantenimiento_equipos",
  name: "CAPUFE — Mantenimiento Equipos Peaje/Telepeaje FONADIN",
  description:
    "Detecta licitaciones de CAPUFE para mantenimiento preventivo y correctivo a equipos de control de tránsito de peaje y telepeaje en plazas de cobro de la red FONADIN y tramo México-Puebla.",
  isActive: true,
  priority: 1,
  scheduleMinutes: 30,
  minScore: 0.25,

  includeTerms: [
    "capufe",
    "caminos y puentes federales",
    "fonadin",
    "red fonadin",
    "fondo nacional de infraestructura",
    "mexico puebla",
    "méxico puebla",
    "tramo mexico puebla",
    "tramo méxico-puebla",
    "mexico-puebla",
    "méxico-puebla",
    "plaza de cobro",
    "plazas de cobro",
    "caseta de cobro",
    "caseta de peaje",
    "casetas de peaje",
    "mantenimiento preventivo",
    "mantenimiento correctivo",
    "mantenimiento preventivo y correctivo",
    "servicio de mantenimiento",
    "mantenimiento a equipo",
    "mantenimiento de equipo",
    "mantenimiento a equipos",
    "mantenimiento de equipos",
    "equipo de control de transito",
    "equipo de control de tránsito",
    "equipos de control de transito",
    "equipos de control de tránsito",
    "control de transito",
    "control de tránsito",
    "sistema de control de transito",
    "dispositivos de control de transito",
    "peaje",
    "telepeaje",
    "sistema de cobro electronico",
    "sistema electronico de cobro",
    "cobro electronico",
    "iave",
    "televia",
    "tag iave",
    "lector rfid",
    "antena rfid",
    "ocr placas",
    "reconocimiento de placas",
    "señalizacion vial",
    "señalización vial",
    "semaforos",
    "semáforos",
    "barreras vehiculares",
    "plumas de caseta",
    "lazos inductivos",
    "sensores de trafico",
    "aforo vehicular",
    "conteo vehicular",
    "cctv caseta",
    "camaras de vigilancia vial",
    "its",
    "sistemas inteligentes de transporte",
  ],

  excludeTerms: [
    "ambulancia",
    "construccion de puente",
    "construccion de autopista",
    "pavimentacion",
    "repavimentacion",
    "obra civil mayor",
    "carpeta asfaltica",
    "puente vehicular nuevo",
  ],

  geoTerms: [],

  entityTerms: [
    "capufe",
    "caminos y puentes federales de ingresos y servicios conexos",
    "fonadin",
    "fondo nacional de infraestructura",
  ],

  rules: [
    {
      ruleType: "entity",
      fieldName: "dependency_name",
      operator: "any_of",
      value: ["capufe", "caminos y puentes", "fonadin"],
      weight: 0.4,
      isRequired: false,
    },
    {
      ruleType: "keyword",
      fieldName: "canonical_text",
      operator: "any_of",
      value: [
        "mantenimiento preventivo",
        "mantenimiento correctivo",
        "control de transito",
        "control de tránsito",
        "peaje",
        "telepeaje",
        "plaza de cobro",
        "plazas de cobro",
        "fonadin",
        "iave",
        "televia",
        "sistema electronico de cobro",
        "semaforos",
        "barreras vehiculares",
        "aforo vehicular",
        "sistema de control de transito",
        "equipos de control",
        "caseta",
        "mexico puebla",
        "méxico-puebla",
      ],
      weight: 0.6,
      isRequired: true,
    },
  ],
};
