/**
 * RADAR: fondos_salud
 * Detecta convocatorias y fondos internacionales para donatarias autorizadas
 * en el sector salud. Nacional, sin filtro geo. minScore bajo para captura máxima.
 */
import type { RadarConfig } from "../types/procurement";

export const fondosSaludRadar: RadarConfig = {
  key: "fondos_salud",
  name: "Fondos Internacionales — Sector Salud",
  description:
    "Detecta convocatorias de donaciones y fondos internacionales orientados al sector salud para donatarias autorizadas en México.",
  isActive: false,
  priority: 2,
  scheduleMinutes: 360, // cada 6 horas, sincronizado con el job de fondos
  minScore: 0.2,

  includeTerms: [
    "salud",
    "médico",
    "medico",
    "hospital",
    "hospitalario",
    "clínica",
    "clinica",
    "bienestar",
    "nutrición",
    "nutricion",
    "prevención",
    "prevencion",
    "discapacidad",
    "rehabilitación",
    "rehabilitacion",
    "salud mental",
    "salud comunitaria",
    "atención médica",
    "atencion medica",
    "medicina",
    "enfermería",
    "enfermeria",
    "paciente",
    "enfermedades",
    "tratamiento",
    "diagnóstico",
    "diagnostico",
    "vacunación",
    "vacunacion",
    "epidemiología",
    "epidemiologia",
    "salud pública",
    "salud publica",
    "primera infancia",
    "materno infantil",
    "maternidad",
    "pediatría",
    "pediatria",
    "oncología",
    "oncologia",
    "cáncer",
    "cancer",
    "diabetes",
    "hipertensión",
    "hipertension",
    "VIH",
    "sida",
    "tuberculosis",
    "enfermedades crónicas",
    "enfermedades cronicas",
    "salud sexual",
    "salud reproductiva",
    "agua y saneamiento",
    "acceso a medicamentos",
    "medicamentos",
    "equipo médico",
    "equipo medico",
    "laboratorio",
    "ciencias de la salud",
  ],

  excludeTerms: [],

  geoTerms: [],

  entityTerms: [],

  rules: [
    {
      ruleType: "keyword",
      fieldName: "canonical_text",
      operator: "any_of",
      value: [
        "salud",
        "médico",
        "medico",
        "hospital",
        "clínica",
        "clinica",
        "bienestar",
        "nutrición",
        "nutricion",
        "prevención",
        "prevencion",
        "discapacidad",
        "rehabilitación",
        "rehabilitacion",
        "salud mental",
        "salud comunitaria",
      ],
      weight: 1.0,
      isRequired: false,
    },
  ],
};
