/**
 * RADAR: fondos_cultura
 * Detecta convocatorias y fondos internacionales para donatarias autorizadas
 * en el sector cultura. Nacional, sin filtro geo. minScore bajo para captura máxima.
 */
import type { RadarConfig } from "../types/procurement";

export const fondosCulturaRadar: RadarConfig = {
  key: "fondos_cultura",
  name: "Fondos Internacionales — Sector Cultura",
  description:
    "Detecta convocatorias de donaciones y fondos internacionales orientados al sector cultura para donatarias autorizadas en México.",
  isActive: true,
  priority: 2,
  scheduleMinutes: 360,
  minScore: 0.2,

  includeTerms: [
    "cultura",
    "cultural",
    "arte",
    "artístico",
    "artistico",
    "patrimonio",
    "patrimonio cultural",
    "museo",
    "biblioteca",
    "música",
    "musica",
    "danza",
    "teatro",
    "artesanía",
    "artesania",
    "tradición",
    "tradicion",
    "diversidad cultural",
    "literatura",
    "poesía",
    "poesia",
    "cine",
    "cine documental",
    "audiovisual",
    "fotografía",
    "fotografia",
    "artes plásticas",
    "artes plasticas",
    "artes visuales",
    "artes escénicas",
    "artes escenicas",
    "performance",
    "circo",
    "ópera",
    "opera",
    "coral",
    "orquesta",
    "banda de música",
    "música tradicional",
    "musica tradicional",
    "folclore",
    "folclor",
    "costumbres",
    "identidad cultural",
    "lenguas indígenas",
    "lenguas indigenas",
    "pueblo indígena",
    "pueblo indigena",
    "comunidad indígena",
    "comunidad indigena",
    "patrimonio inmaterial",
    "patrimonio material",
    "conservación patrimonio",
    "restauración",
    "restauracion",
    "galería",
    "galeria",
    "exposición",
    "exposicion",
    "festival cultural",
    "festival de arte",
    "creación artística",
    "creacion artistica",
    "expresión cultural",
    "expresion cultural",
    "mediación cultural",
    "mediacion cultural",
    "educación artística",
    "educacion artistica",
    "gestión cultural",
    "gestion cultural",
    "industrias creativas",
    "economia creativa",
    "economía creativa",
    "turismo cultural",
    "sitios históricos",
    "sitios historicos",
    "arqueología",
    "arqueologia",
    "INAH",
    "bellas artes",
    "CONACULTA",
    "Secretaría de Cultura",
    "Secretaria de Cultura",
    "fomento cultural",
    "difusión cultural",
    "difusion cultural",
  ],

  excludeTerms: [],

  geoTerms: [],

  entityTerms: [],

  rules: [
    {
      ruleType: "keyword",
      fieldName: "canonical_text",
      operator: "any_of",
      value: [
        "cultura",
        "cultural",
        "arte",
        "artístico",
        "artistico",
        "patrimonio",
        "museo",
        "biblioteca",
        "música",
        "musica",
        "danza",
        "teatro",
        "artesanía",
        "artesania",
        "tradición",
        "tradicion",
        "diversidad cultural",
      ],
      weight: 1.0,
      isRequired: false,
    },
  ],
};
