/**
 * RADAR: fondos_deporte
 * Detecta convocatorias y fondos internacionales para donatarias autorizadas
 * en el sector deporte. Nacional, sin filtro geo. minScore bajo para captura máxima.
 */
import type { RadarConfig } from "../types/procurement";

export const fondosDeporteRadar: RadarConfig = {
  key: "fondos_deporte",
  name: "Fondos Internacionales — Sector Deporte",
  description:
    "Detecta convocatorias de donaciones y fondos internacionales orientados al sector deporte para donatarias autorizadas en México.",
  isActive: false,
  priority: 2,
  scheduleMinutes: 360,
  minScore: 0.2,

  includeTerms: [
    "deporte",
    "deportivo",
    "deportiva",
    "atleta",
    "actividad física",
    "actividad fisica",
    "recreación",
    "recreacion",
    "entrenamiento",
    "competencia deportiva",
    "educación física",
    "educacion fisica",
    "inclusión deportiva",
    "inclusion deportiva",
    "alto rendimiento",
    "rendimiento deportivo",
    "olimpiada",
    "paralímpico",
    "paralimpico",
    "juegos deportivos",
    "liga deportiva",
    "fútbol",
    "futbol",
    "basquetbol",
    "béisbol",
    "beisbol",
    "natación",
    "natacion",
    "atletismo",
    "ciclismo",
    "karate",
    "boxeo",
    "judo",
    "lucha",
    "taekwondo",
    "voleibol",
    "tenis",
    "golf",
    "equitación",
    "equitacion",
    "esgrima",
    "halterofilia",
    "tiro",
    "arquería",
    "arqueria",
    "remo",
    "clavados",
    "gimnasia",
    "cultura física",
    "cultura fisica",
    "instalaciones deportivas",
    "infraestructura deportiva",
    "cancha",
    "estadio",
    "alberca",
    "deporte adaptado",
    "deporte para todos",
    "deporte escolar",
    "deporte comunitario",
    "vida activa",
    "salud y deporte",
  ],

  excludeTerms: [],

  geoTerms: [],

  entityTerms: [],

  rules: [
    {
      ruleType: "keyword",
      fieldName: "canonical_text",
      operator: "any_of",
      value: [
        "deporte",
        "deportivo",
        "atleta",
        "actividad física",
        "actividad fisica",
        "recreación",
        "recreacion",
        "entrenamiento",
        "competencia deportiva",
        "educación física",
        "educacion fisica",
        "inclusión deportiva",
        "inclusion deportiva",
      ],
      weight: 1.0,
      isRequired: false,
    },
  ],
};
